# -*- coding: utf-8 -*-
"""All.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eNBJUOoz0-XSXu1DsTk5t_4-IZ9WNlWK
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('/content/data.csv')

print(df)

df.head(5)

df.tail(5)

df.sample(5)

df.shape

df.info()

df.describe()

df.dtypes

df.isnull().sum()

df['Gender'].replace('M', 'Male',inplace=True)
df['Gender'].replace('F', 'Female',inplace=True)

#handling missing values
df['1st'].fillna(df['1st'].median(),inplace=True)
df['2nd'].fillna(df['2nd'].mean(),inplace=True)
df['5th'].fillna(df['5th'].mode()[0],inplace=True)

#FOCB
df['3rd']=df['3rd'].ffill()
df['Gender']=df['Gender'].ffill()

#LOCF
df['4th']=df['4th'].bfill()

#Combining similar column
df['Roll no.']=df['Roll no.'].fillna(0)
df['Roll']=df['Roll'].fillna(0)
df['Roll No.'] = df['Roll'] + df['Roll no.']
df['Roll no.']=df['Roll No.']

df=df.drop('Roll',axis=1)
df=df.drop('Roll No.',axis=1)

df

#Aggregration
def x1(y):
  return y.quantile(0.25)
def x2(y):
  return y.quantile(0.5)
def x3(y):
  return y.quantile(0.75)
x=df.groupby("Gender").agg(['mean','median','min','max','std',x1,x2,x3])
x

sns.histplot(df['1st'],color='skyblue')

sns.boxplot(x='Gender',y='2nd',data=df)

convert_dict = {'College Code': str,
                'Roll no.': str,
                'Subject Code':str
                }

df = df.astype(convert_dict)

df.hist(figsize=(10,8))
plt.show()

df.boxplot(figsize=(10,8))
plt.show()