# -*- coding: utf-8 -*-
"""pract_8and9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9b4Ed435eKNPUthgtTInOAnPS08wU0l
"""

import pandas as pd
import seaborn as sns
titanic = sns.load_dataset("titanic")

titanic

import matplotlib.pyplot as plt

sns.histplot(titanic["fare"],bins=50,kde=True,color='red')
plt.title("Distribution of Ticket Price on Titanic")
plt.xlabel("Fare")
plt.ylabel("Frequency")
plt.show()

sns.boxplot(x="sex",y="age",hue="survived",data=titanic)
plt.title("Age Distribution according to Gender and Survival Status on Titanic")
plt.xlabel("Age")
plt.ylabel("Gender")
plt.legend(title='Survived',loc='upper right')
plt.show()